-- Seed · Spiritual-gifts v2 — personality-style personas + an expanded bank.
-- Personas give each gift a "type" identity (name, summary, strengths, serving).
-- The bank grows to ~7 items per gift (≈49 total) so each member can be served a
-- shuffled, weighted subset of ~20. Idempotent on code / gift_key.

-- ── Personas (one per gift) ─────────────────────────────────────────────────
INSERT INTO gift_definitions (gift_key, title, persona_name, tagline, summary, strengths, serving, emoji, color, sort) VALUES
  ('leadership', 'Leadership', 'The Shepherd-Leader',
   'You see where the family is going and help everyone move together.',
   'You carry vision and people at the same time. When a group stalls, something in you rises to bring order, set direction, and call others into their part. You are not after a title — you are after the destination, and you want to take everyone with you. People feel safer and clearer when you are in the room.',
   ARRAY['Casts vision others can follow','Brings order to confusion','Raises and releases new leaders','Owns the outcome, not the credit'],
   ARRAY['Lead a cell group on the multiplication pathway','Coordinate a ministry team or project','Mentor an emerging leader'],
   '🧭', '#6366F1', 1),
  ('teaching', 'Teaching', 'The Teacher',
   'You make the deep things of God simple and unforgettable.',
   'You cannot help but study, and you cannot keep what you learn to yourself. You love the moment a hard truth suddenly makes sense on someone''s face. You break big things into clear steps, and you guard the truth carefully. People leave your conversations understanding the Word better than before.',
   ARRAY['Explains Scripture so it clicks','Turns big truths into simple steps','Loves to study and prepare','Anchors people in sound truth'],
   ARRAY['Teach a pathway class or module discussion','Disciple a new believer one-to-one','Help shape teaching content'],
   '📖', '#0B84E8', 2),
  ('service', 'Service', 'The Servant',
   'You see the practical need and quietly meet it.',
   'You notice what others miss — the chairs not set, the task left undone — and you simply handle it. You would rather work behind the scenes than be seen, and you feel most alive when something runs well because you were there. Your hands carry the love of God.',
   ARRAY['Spots practical needs first','Happy behind the scenes','Reliable and follows through','Energised by being useful'],
   ARRAY['Join the service & operations team','Help with setup, logistics or media','Support a ministry that needs hands'],
   '🤲', '#22B07D', 3),
  ('mercy', 'Mercy', 'The Comforter',
   'You move toward people in pain and stay with them.',
   'You feel what others feel, often before they say a word. The hurting, the grieving, the overlooked — you are drawn to them, and you carry the comfort of God into hard places. Where others step back, you sit down. Your presence itself is a ministry.',
   ARRAY['Senses unspoken pain','Stays with people in suffering','Carries deep compassion','Brings calm and comfort'],
   ARRAY['Join care & visitation','Follow up members who are struggling','Walk with the grieving or sick'],
   '💗', '#E0567A', 4),
  ('evangelism', 'Evangelism', 'The Messenger',
   'You light up sharing Jesus with people far from Him.',
   'You see every conversation as a door. Telling people about Jesus does not drain you — it fuels you. You pray for specific people by name and look for natural openings to share. Heaven feels close when someone takes their first step toward Christ because of you.',
   ARRAY['Finds natural openings for the gospel','Energised by reaching the lost','Prays for people by name','Bold and warm with outsiders'],
   ARRAY['Join outreach & missions','Lead follow-up of new converts','Help plan community outreach'],
   '📣', '#E07B39', 5),
  ('giving', 'Giving', 'The Provider',
   'You fuel the mission with joyful, strategic generosity.',
   'You see your resources as God''s tools, and you give with joy — often quietly, often beyond what is expected. You have an eye for kingdom needs and a heart that loves to meet them. Where you invest, the mission moves forward.',
   ARRAY['Gives joyfully and generously','Stewards resources wisely','Senses needs to meet quietly','Funds the mission strategically'],
   ARRAY['Become a kingdom partner','Fund a project or mission','Help with stewardship & resourcing'],
   '🎁', '#C89B3C', 6),
  ('hospitality', 'Hospitality', 'The Welcomer',
   'You make every person feel they belong.',
   'You notice the one standing alone and go to them. Opening your home, your table, your circle comes naturally — and people relax in your warmth. You turn strangers into family and rooms into homes. Belonging follows you.',
   ARRAY['Makes newcomers feel at home','Opens home and table easily','Notices and includes the outsider','Creates warmth and belonging'],
   ARRAY['Join the welcome & hospitality team','Host a cell or newcomers'' meal','Lead new-member follow-up'],
   '🫶', '#0F766E', 7)
ON CONFLICT (gift_key) DO UPDATE SET
  title = EXCLUDED.title, persona_name = EXCLUDED.persona_name, tagline = EXCLUDED.tagline,
  summary = EXCLUDED.summary, strengths = EXCLUDED.strengths, serving = EXCLUDED.serving,
  emoji = EXCLUDED.emoji, color = EXCLUDED.color, sort = EXCLUDED.sort;

-- ── Expanded bank (≈4 more per gift on top of the 3 in 05_gifts.sql) ────────
INSERT INTO gift_questions (code, gift_key, prompt, sort) VALUES
  ('lead_4',  'leadership',  'When plans fall apart, I instinctively step up to reorganise the group.', 22),
  ('lead_5',  'leadership',  'I think about where our church or cell should be a year from now.', 23),
  ('lead_6',  'leadership',  'I would rather develop other leaders than do everything myself.', 24),
  ('lead_7',  'leadership',  'People follow through when I take responsibility for a goal.', 25),
  ('teach_4', 'teaching',    'I dig into the background of a passage so I can explain it well.', 26),
  ('teach_5', 'teaching',    'I get frustrated when the Word is taught carelessly or vaguely.', 27),
  ('teach_6', 'teaching',    'I enjoy preparing notes, illustrations or questions to help people learn.', 28),
  ('teach_7', 'teaching',    'Friends come to me to understand what a Bible passage means.', 29),
  ('serve_4', 'service',     'I feel satisfied when a task is done well, even if no one notices.', 30),
  ('serve_5', 'service',     'I quietly finish jobs others started and left undone.', 31),
  ('serve_6', 'service',     'Practical help is how I most naturally show love.', 32),
  ('serve_7', 'service',     'I prefer a clear task to handle over being up front.', 33),
  ('mercy_4', 'mercy',       'I carry people''s burdens with me long after we talk.', 34),
  ('mercy_5', 'mercy',       'I am patient with people who are weak, broken or slow to heal.', 35),
  ('mercy_6', 'mercy',       'I would rather comfort one hurting person than address a crowd.', 36),
  ('mercy_7', 'mercy',       'I notice the person everyone else has overlooked.', 37),
  ('evang_4', 'evangelism',  'I feel a holy restlessness for people who don''t yet know Jesus.', 38),
  ('evang_5', 'evangelism',  'I can turn an everyday conversation toward faith without forcing it.', 39),
  ('evang_6', 'evangelism',  'I keep a mental list of people I am praying will meet Christ.', 40),
  ('evang_7', 'evangelism',  'Sharing my testimony comes easily and joyfully.', 41),
  ('give_4',  'giving',      'I plan my finances so I can respond when God prompts me to give.', 42),
  ('give_5',  'giving',      'Seeing a need met because I gave brings me deep joy.', 43),
  ('give_6',  'giving',      'I am content with less so I can give more to the mission.', 44),
  ('give_7',  'giving',      'I look for kingdom projects worth investing in.', 45),
  ('hosp_4',  'hospitality', 'My home is often open to others — meals, stays, gatherings.', 46),
  ('hosp_5',  'hospitality', 'I instinctively make sure no one is left out of the circle.', 47),
  ('hosp_6',  'hospitality', 'New people remember me as the one who made them feel welcome.', 48),
  ('hosp_7',  'hospitality', 'Creating a warm, belonging atmosphere energises me.', 49)
ON CONFLICT (code) DO NOTHING;
