-- A Year of Verses — a 365-day daily-verse plan (one verse per calendar day,
-- starting 2026-06-25). Each row is the verse for its day_date. Drives the Home
-- "Verse for today"; after the plan ends the personalized picker takes over.
-- Sourced from the supplied PDF; references/versions/text transcribed verbatim.

-- Up Migration

CREATE TABLE daily_verses (
  day_index  INT PRIMARY KEY,
  day_date   DATE NOT NULL UNIQUE,
  theme      TEXT NOT NULL,
  reference  TEXT NOT NULL,
  version    TEXT NOT NULL,
  verse_text TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX daily_verses_date_idx ON daily_verses (day_date);

INSERT INTO daily_verses (day_index, day_date, theme, reference, version, verse_text) VALUES
(1, DATE '2026-06-25', 'JOY & HAPPINESS', 'Nehemiah 8:10', 'NIV', 'Do not grieve, for the joy of the LORD is your strength.'),
(2, DATE '2026-06-26', 'PEACE & CALM', 'John 14:27', 'NIV', 'Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.'),
(3, DATE '2026-06-27', 'SECURITY & SAFETY', 'Psalm 91:1-2', 'NIV', 'Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the LORD, He is my refuge and my fortress, my God, in whom I trust.'),
(4, DATE '2026-06-28', 'ANGER & SELF-CONTROL', 'Ephesians 4:26-27', 'NIV', 'In your anger do not sin: Do not let the sun go down while you are still angry, and do not give the devil a foothold.'),
(5, DATE '2026-06-29', 'SADNESS & GRIEF', 'Psalm 34:18', 'NIV', 'The LORD is close to the brokenhearted and saves those who are crushed in spirit.'),
(6, DATE '2026-06-30', 'FEAR & ANXIETY', 'Isaiah 41:10', 'NIV', 'So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.'),
(7, DATE '2026-07-01', 'HOPE', 'Jeremiah 29:11', 'NIV', 'For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.'),
(8, DATE '2026-07-02', 'LOVE', '1 Corinthians 13:4-5', 'NIV', 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs.'),
(9, DATE '2026-07-03', 'COMFORT IN SUFFERING', 'Psalm 119:50', 'NIV', 'My comfort in my suffering is this: Your promise preserves my life.'),
(10, DATE '2026-07-04', 'GRATITUDE & THANKFULNESS', '1 Thessalonians 5:18', 'NIV', 'Give thanks in all circumstances; for this is God''s will for you in Christ Jesus.'),
(11, DATE '2026-07-05', 'COURAGE & STRENGTH', 'Philippians 4:13', 'NIV', 'I can do all this through him who gives me strength.'),
(12, DATE '2026-07-06', 'LONELINESS', 'Deuteronomy 31:8', 'NIV', 'The LORD himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged.'),
(13, DATE '2026-07-07', 'FORGIVENESS', '1 John 1:9', 'NIV', 'If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.'),
(14, DATE '2026-07-08', 'PATIENCE', 'Romans 12:12', 'NIV', 'Be joyful in hope, patient in affliction, faithful in prayer.'),
(15, DATE '2026-07-09', 'CONTENTMENT', 'Philippians 4:11-12', 'NIV', 'I have learned to be content whatever the circumstances. I know what it is to be in need, and I know what it is to have plenty.'),
(16, DATE '2026-07-10', 'DOUBT & FAITH', 'Mark 9:24', 'NIV', 'Immediately the boy''s father exclaimed, I do believe; help me overcome my unbelief!'),
(17, DATE '2026-07-11', 'GUILT & SHAME', 'Romans 8:1', 'NIV', 'Therefore, there is now no condemnation for those who are in Christ Jesus.'),
(18, DATE '2026-07-12', 'WORRY & STRESS', 'Matthew 6:25', 'NIV', 'Therefore I tell you, do not worry about your life, what you will eat or drink; or about your body, what you will wear. Is not life more than food, and the body more than clothes?'),
(19, DATE '2026-07-13', 'TRUST IN GOD', 'Proverbs 3:5-6', 'ESV', 'Trust in the LORD with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.'),
(20, DATE '2026-07-14', 'DISCOURAGEMENT & WEARINESS', 'Galatians 6:9', 'NIV', 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.'),
(21, DATE '2026-07-15', 'CONFIDENCE & IDENTITY', 'Psalm 139:14', 'NIV', 'I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.'),
(22, DATE '2026-07-16', 'JEALOUSY & ENVY', 'Proverbs 14:30', 'NIV', 'A heart at peace gives life to the body, but envy rots the bones.'),
(23, DATE '2026-07-17', 'TEMPTATION', '1 Corinthians 10:13', 'NIV', 'No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear. But when you are tempted, he will also provide a way out.'),
(24, DATE '2026-07-18', 'MARRIAGE & RELATIONSHIPS', 'Ecclesiastes 4:9-10', 'NIV', 'Two are better than one, because they have a good return for their labor: If either of them falls down, one can help the other up.'),
(25, DATE '2026-07-19', 'FAMILY & PARENTING', 'Proverbs 22:6', 'NIV', 'Start children off on the way they should go, and even when they are old they will not turn from it.'),
(26, DATE '2026-07-20', 'FINANCES & PROVISION', 'Philippians 4:19', 'NIV', 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.'),
(27, DATE '2026-07-21', 'HEALING & HEALTH', 'Jeremiah 30:17', 'NIV', 'But I will restore you to health and heal your wounds, declares the LORD.'),
(28, DATE '2026-07-22', 'WORK & DILIGENCE', 'Colossians 3:23', 'NIV', 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.'),
(29, DATE '2026-07-23', 'WISDOM & DECISIONS', 'James 1:5', 'NIV', 'If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.'),
(30, DATE '2026-07-24', 'FRIENDSHIP', 'Proverbs 17:17', 'NIV', 'A friend loves at all times, and a brother is born for a time of adversity.'),
(31, DATE '2026-07-25', 'GENEROSITY & GIVING', '2 Corinthians 9:7', 'NIV', 'Each of you should give what you have decided in your heart to give, not reluctantly or under compulsion, for God loves a cheerful giver.'),
(32, DATE '2026-07-26', 'HUMILITY', 'James 4:10', 'NIV', 'Humble yourselves before the Lord, and he will lift you up.'),
(33, DATE '2026-07-27', 'PRAISE & WORSHIP', 'Psalm 150:6', 'NIV', 'Let everything that has breath praise the LORD. Praise the LORD.'),
(34, DATE '2026-07-28', 'PRAYER', 'Matthew 7:7', 'NIV', 'Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.'),
(35, DATE '2026-07-29', 'REST & SLEEP', 'Matthew 11:28-29', 'NIV', 'Come to me, all you who are weary and burdened, and I will give you rest. Take my yoke upon you and learn from me, and you will find rest for your souls.'),
(36, DATE '2026-07-30', 'NEW BEGINNINGS', 'Isaiah 43:19', 'NIV', 'See, I am doing a new thing! Now it springs up; do you not perceive it? I am making a way in the wilderness and streams in the wasteland.'),
(37, DATE '2026-07-31', 'PERSEVERANCE', 'Romans 5:3-4', 'NIV', 'We also glory in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope.'),
(38, DATE '2026-08-01', 'JOY & HAPPINESS', 'Psalm 16:11', 'ESV', 'You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore.'),
(39, DATE '2026-08-02', 'PEACE & CALM', 'Philippians 4:7', 'ESV', 'And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.'),
(40, DATE '2026-08-03', 'SECURITY & SAFETY', 'Proverbs 18:10', 'ESV', 'The name of the LORD is a strong tower; the righteous man runs into it and is safe.'),
(41, DATE '2026-08-04', 'ANGER & SELF-CONTROL', 'James 1:19-20', 'ESV', 'Let every person be quick to hear, slow to speak, slow to anger; for the anger of man does not produce the righteousness of God.'),
(42, DATE '2026-08-05', 'SADNESS & GRIEF', 'Matthew 5:4', 'ESV', 'Blessed are those who mourn, for they shall be comforted.'),
(43, DATE '2026-08-06', 'FEAR & ANXIETY', 'Philippians 4:6-7', 'NIV', 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.'),
(44, DATE '2026-08-07', 'HOPE', 'Romans 15:13', 'NIV', 'May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.'),
(45, DATE '2026-08-08', 'LOVE', 'John 3:16', 'KJV', 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.'),
(46, DATE '2026-08-09', 'COMFORT IN SUFFERING', 'Romans 8:18', 'ESV', 'For I consider that the sufferings of this present time are not worth comparing with the glory that is to be revealed to us.'),
(47, DATE '2026-08-10', 'GRATITUDE & THANKFULNESS', 'Psalm 100:4', 'ESV', 'Enter his gates with thanksgiving, and his courts with praise! Give thanks to him; bless his name!'),
(48, DATE '2026-08-11', 'COURAGE & STRENGTH', 'Isaiah 40:29', 'NIV', 'He gives strength to the weary and increases the power of the weak.'),
(49, DATE '2026-08-12', 'LONELINESS', 'Hebrews 13:5', 'ESV', 'I will never leave you nor forsake you.'),
(50, DATE '2026-08-13', 'FORGIVENESS', 'Ephesians 4:32', 'ESV', 'Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you.'),
(51, DATE '2026-08-14', 'PATIENCE', 'Galatians 6:9', 'ESV', 'And let us not grow weary of doing good, for in due season we will reap, if we do not give up.'),
(52, DATE '2026-08-15', 'CONTENTMENT', '1 Timothy 6:6', 'ESV', 'But godliness with contentment is great gain.'),
(53, DATE '2026-08-16', 'DOUBT & FAITH', 'Hebrews 11:6', 'ESV', 'And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him.'),
(54, DATE '2026-08-17', 'GUILT & SHAME', 'Isaiah 61:7', 'NIV', 'Instead of your shame you will receive a double portion, and instead of disgrace you will rejoice in your inheritance.'),
(55, DATE '2026-08-18', 'WORRY & STRESS', 'Matthew 11:28', 'KJV', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'),
(56, DATE '2026-08-19', 'TRUST IN GOD', 'Psalm 9:10', 'NIV', 'Those who know your name trust in you, for you, LORD, have never forsaken those who seek you.'),
(57, DATE '2026-08-20', 'DISCOURAGEMENT & WEARINESS', 'Isaiah 40:31', 'ESV', 'But they who wait for the LORD shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.'),
(58, DATE '2026-08-21', 'CONFIDENCE & IDENTITY', 'Ephesians 2:10', 'NIV', 'For we are God''s handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.'),
(59, DATE '2026-08-22', 'JEALOUSY & ENVY', 'James 3:16', 'ESV', 'For where jealousy and selfish ambition exist, there will be disorder and every vile practice.'),
(60, DATE '2026-08-23', 'TEMPTATION', 'James 1:12', 'ESV', 'Blessed is the man who remains steadfast under trial, for when he has stood the test he will receive the crown of life, which God has promised to those who love him.'),
(61, DATE '2026-08-24', 'MARRIAGE & RELATIONSHIPS', '1 Corinthians 13:7', 'ESV', 'Love bears all things, believes all things, hopes all things, endures all things.'),
(62, DATE '2026-08-25', 'FAMILY & PARENTING', 'Joshua 24:15', 'KJV', 'As for me and my house, we will serve the LORD.'),
(63, DATE '2026-08-26', 'FINANCES & PROVISION', 'Matthew 6:33', 'KJV', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.'),
(64, DATE '2026-08-27', 'HEALING & HEALTH', 'Psalm 103:2-3', 'ESV', 'Bless the LORD, O my soul, and forget not all his benefits, who forgives all your iniquity, who heals all your diseases.'),
(65, DATE '2026-08-28', 'WORK & DILIGENCE', 'Proverbs 16:3', 'ESV', 'Commit your work to the LORD, and your plans will be established.'),
(66, DATE '2026-08-29', 'WISDOM & DECISIONS', 'Proverbs 3:5-6', 'KJV', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.'),
(67, DATE '2026-08-30', 'FRIENDSHIP', 'Proverbs 27:17', 'ESV', 'Iron sharpens iron, and one man sharpens another.'),
(68, DATE '2026-08-31', 'GENEROSITY & GIVING', 'Acts 20:35', 'KJV', 'It is more blessed to give than to receive.'),
(69, DATE '2026-09-01', 'HUMILITY', 'Philippians 2:3', 'ESV', 'Do nothing from selfish ambition or conceit, but in humility count others more significant than yourselves.'),
(70, DATE '2026-09-02', 'PRAISE & WORSHIP', 'Psalm 95:1', 'ESV', 'Oh come, let us sing to the LORD; let us make a joyful noise to the rock of our salvation!'),
(71, DATE '2026-09-03', 'PRAYER', '1 Thessalonians 5:17', 'KJV', 'Pray without ceasing.'),
(72, DATE '2026-09-04', 'REST & SLEEP', 'Psalm 127:2', 'NIV', 'In vain you rise early and stay up late, toiling for food to eat, for he grants sleep to those he loves.'),
(73, DATE '2026-09-05', 'NEW BEGINNINGS', '2 Corinthians 5:17', 'ESV', 'Therefore, if anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.'),
(74, DATE '2026-09-06', 'PERSEVERANCE', 'Hebrews 12:1', 'ESV', 'Let us run with endurance the race that is set before us, looking to Jesus, the founder and perfecter of our faith.'),
(75, DATE '2026-09-07', 'JOY & HAPPINESS', 'Psalm 30:5', 'NLT', 'Weeping may last through the night, but joy comes with the morning.'),
(76, DATE '2026-09-08', 'PEACE & CALM', 'Isaiah 26:3', 'KJV', 'Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.'),
(77, DATE '2026-09-09', 'SECURITY & SAFETY', 'Psalm 46:1', 'NIV', 'God is our refuge and strength, an ever-present help in trouble.'),
(78, DATE '2026-09-10', 'ANGER & SELF-CONTROL', 'Proverbs 15:1', 'KJV', 'A soft answer turneth away wrath: but grievous words stir up anger.'),
(79, DATE '2026-09-11', 'SADNESS & GRIEF', 'Psalm 147:3', 'NIV', 'He heals the brokenhearted and binds up their wounds.'),
(80, DATE '2026-09-12', 'FEAR & ANXIETY', 'Psalm 23:4', 'KJV', 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.'),
(81, DATE '2026-09-13', 'HOPE', 'Lamentations 3:22-23', 'ESV', 'The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.'),
(82, DATE '2026-09-14', 'LOVE', '1 John 4:18', 'ESV', 'There is no fear in love, but perfect love casts out fear. For fear has to do with punishment, and whoever fears has not been perfected in love.'),
(83, DATE '2026-09-15', 'COMFORT IN SUFFERING', '2 Corinthians 4:17', 'NIV', 'For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.'),
(84, DATE '2026-09-16', 'GRATITUDE & THANKFULNESS', 'Psalm 107:1', 'KJV', 'O give thanks unto the LORD, for he is good: for his mercy endureth for ever.'),
(85, DATE '2026-09-17', 'COURAGE & STRENGTH', 'Psalm 18:32', 'ESV', 'The God who equipped me with strength and made my way blameless.'),
(86, DATE '2026-09-18', 'LONELINESS', 'Psalm 68:6', 'NIV', 'God sets the lonely in families, he leads out the prisoners with singing.'),
(87, DATE '2026-09-19', 'FORGIVENESS', 'Colossians 3:13', 'NIV', 'Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.'),
(88, DATE '2026-09-20', 'PATIENCE', 'Psalm 37:7', 'NIV', 'Be still before the LORD and wait patiently for him; do not fret when people succeed in their ways, when they carry out their wicked schemes.'),
(89, DATE '2026-09-21', 'CONTENTMENT', 'Hebrews 13:5', 'NIV', 'Keep your lives free from the love of money and be content with what you have, because God has said, Never will I leave you; never will I forsake you.'),
(90, DATE '2026-09-22', 'DOUBT & FAITH', 'James 1:6', 'NIV', 'But when you ask, you must believe and not doubt, because the one who doubts is like a wave of the sea, blown and tossed by the wind.'),
(91, DATE '2026-09-23', 'GUILT & SHAME', 'Psalm 34:5', 'ESV', 'Those who look to him are radiant, and their faces shall never be ashamed.'),
(92, DATE '2026-09-24', 'WORRY & STRESS', 'Psalm 55:22', 'NIV', 'Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken.'),
(93, DATE '2026-09-25', 'TRUST IN GOD', 'Psalm 37:5', 'KJV', 'Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.'),
(94, DATE '2026-09-26', 'DISCOURAGEMENT & WEARINESS', 'Psalm 42:5', 'NIV', 'Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God.'),
(95, DATE '2026-09-27', 'CONFIDENCE & IDENTITY', 'Jeremiah 1:5', 'ESV', 'Before I formed you in the womb I knew you, and before you were born I consecrated you.'),
(96, DATE '2026-09-28', 'JEALOUSY & ENVY', '1 Corinthians 13:4', 'NIV', 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.'),
(97, DATE '2026-09-29', 'TEMPTATION', 'Matthew 26:41', 'KJV', 'Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak.'),
(98, DATE '2026-09-30', 'MARRIAGE & RELATIONSHIPS', 'Ephesians 5:25', 'NIV', 'Husbands, love your wives, just as Christ loved the church and gave himself up for her.'),
(99, DATE '2026-10-01', 'FAMILY & PARENTING', 'Deuteronomy 6:6-7', 'ESV', 'And these words that I command you today shall be on your heart. You shall teach them diligently to your children, and shall talk of them when you sit in your house.'),
(100, DATE '2026-10-02', 'FINANCES & PROVISION', 'Proverbs 3:9-10', 'NIV', 'Honor the LORD with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing.'),
(101, DATE '2026-10-03', 'HEALING & HEALTH', 'Isaiah 53:5', 'KJV', 'But he was wounded for our transgressions, he was bruised for our iniquities... and with his stripes we are healed.'),
(102, DATE '2026-10-04', 'WORK & DILIGENCE', 'Ecclesiastes 9:10', 'KJV', 'Whatsoever thy hand findeth to do, do it with thy might.'),
(103, DATE '2026-10-05', 'WISDOM & DECISIONS', 'Proverbs 2:6', 'ESV', 'For the LORD gives wisdom; from his mouth come knowledge and understanding.'),
(104, DATE '2026-10-06', 'FRIENDSHIP', 'John 15:13', 'KJV', 'Greater love hath no man than this, that a man lay down his life for his friends.'),
(105, DATE '2026-10-07', 'GENEROSITY & GIVING', 'Proverbs 11:25', 'ESV', 'Whoever brings blessing will be enriched, and one who waters will himself be watered.'),
(106, DATE '2026-10-08', 'HUMILITY', 'Proverbs 11:2', 'NIV', 'When pride comes, then comes disgrace, but with humility comes wisdom.'),
(107, DATE '2026-10-09', 'PRAISE & WORSHIP', 'Psalm 34:1', 'KJV', 'I will bless the LORD at all times: his praise shall continually be in my mouth.'),
(108, DATE '2026-10-10', 'PRAYER', 'Philippians 4:6', 'ESV', 'Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God.'),
(109, DATE '2026-10-11', 'REST & SLEEP', 'Exodus 33:14', 'ESV', 'And he said, My presence will go with you, and I will give you rest.'),
(110, DATE '2026-10-12', 'NEW BEGINNINGS', 'Lamentations 3:22-23', 'NIV', 'Because of the LORD''s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.'),
(111, DATE '2026-10-13', 'PERSEVERANCE', 'James 1:4', 'NIV', 'Let perseverance finish its work so that you may be mature and complete, not lacking anything.'),
(112, DATE '2026-10-14', 'JOY & HAPPINESS', 'Psalm 118:24', 'KJV', 'This is the day which the LORD hath made; we will rejoice and be glad in it.'),
(113, DATE '2026-10-15', 'PEACE & CALM', 'Psalm 4:8', 'NLT', 'In peace I will lie down and sleep, for you alone, O LORD, will keep me safe.'),
(114, DATE '2026-10-16', 'SECURITY & SAFETY', 'Psalm 121:7-8', 'ESV', 'The LORD will keep you from all evil; he will keep your life. The LORD will keep your going out and your coming in from this time forth and forevermore.'),
(115, DATE '2026-10-17', 'ANGER & SELF-CONTROL', 'Proverbs 14:29', 'NIV', 'Whoever is patient has great understanding, but one who is quick-tempered displays folly.'),
(116, DATE '2026-10-18', 'SADNESS & GRIEF', 'Revelation 21:4', 'NLT', 'He will wipe every tear from their eyes, and there will be no more death or sorrow or crying or pain. All these things are gone forever.'),
(117, DATE '2026-10-19', 'FEAR & ANXIETY', '2 Timothy 1:7', 'KJV', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.'),
(118, DATE '2026-10-20', 'HOPE', 'Romans 8:28', 'NIV', 'And we know that in all things God works for the good of those who love him, who have been called according to his purpose.'),
(119, DATE '2026-10-21', 'LOVE', 'Romans 8:38-39', 'NIV', 'For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, will be able to separate us from the love of God.'),
(120, DATE '2026-10-22', 'COMFORT IN SUFFERING', 'Psalm 34:19', 'ESV', 'Many are the afflictions of the righteous, but the LORD delivers him out of them all.'),
(121, DATE '2026-10-23', 'GRATITUDE & THANKFULNESS', 'Colossians 3:17', 'NIV', 'And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.'),
(122, DATE '2026-10-24', 'COURAGE & STRENGTH', 'Joshua 1:9', 'ESV', 'Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the LORD your God is with you wherever you go.'),
(123, DATE '2026-10-25', 'LONELINESS', 'Matthew 28:20', 'NIV', 'And surely I am with you always, to the very end of the age.'),
(124, DATE '2026-10-26', 'FORGIVENESS', 'Psalm 103:12', 'NLT', 'He has removed our sins as far from us as the east is from the west.'),
(125, DATE '2026-10-27', 'PATIENCE', 'James 5:7', 'ESV', 'Be patient, therefore, brothers, until the coming of the Lord. See how the farmer waits for the precious fruit of the earth, being patient about it.'),
(126, DATE '2026-10-28', 'CONTENTMENT', 'Psalm 23:1', 'KJV', 'The LORD is my shepherd; I shall not want.'),
(127, DATE '2026-10-29', 'DOUBT & FAITH', '2 Corinthians 5:7', 'KJV', 'For we walk by faith, not by sight.'),
(128, DATE '2026-10-30', 'GUILT & SHAME', '2 Corinthians 5:17', 'NIV', 'Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!'),
(129, DATE '2026-10-31', 'WORRY & STRESS', 'Matthew 6:27', 'ESV', 'And which of you by being anxious can add a single hour to his span of life?'),
(130, DATE '2026-11-01', 'TRUST IN GOD', 'Isaiah 26:4', 'NIV', 'Trust in the LORD forever, for the LORD, the LORD himself, is the Rock eternal.'),
(131, DATE '2026-11-02', 'DISCOURAGEMENT & WEARINESS', '2 Corinthians 4:16', 'NIV', 'Therefore we do not lose heart. Though outwardly we are wasting away, yet inwardly we are being renewed day by day.'),
(132, DATE '2026-11-03', 'CONFIDENCE & IDENTITY', '1 Peter 2:9', 'NIV', 'But you are a chosen people, a royal priesthood, a holy nation, God''s special possession, that you may declare the praises of him who called you out of darkness into his wonderful light.'),
(133, DATE '2026-11-04', 'JEALOUSY & ENVY', 'Galatians 5:26', 'ESV', 'Let us not become conceited, provoking one another, envying one another.'),
(134, DATE '2026-11-05', 'TEMPTATION', 'Hebrews 4:15', 'NIV', 'For we do not have a high priest who is unable to empathize with our weaknesses, but we have one who has been tempted in every way, just as we are, yet he did not sin.'),
(135, DATE '2026-11-06', 'MARRIAGE & RELATIONSHIPS', 'Colossians 3:14', 'NIV', 'And over all these virtues put on love, which binds them all together in perfect unity.'),
(136, DATE '2026-11-07', 'FAMILY & PARENTING', 'Psalm 127:3', 'NIV', 'Children are a heritage from the LORD, offspring a reward from him.'),
(137, DATE '2026-11-08', 'FINANCES & PROVISION', 'Malachi 3:10', 'NIV', 'Bring the whole tithe into the storehouse... Test me in this, says the LORD Almighty, and see if I will not throw open the floodgates of heaven.'),
(138, DATE '2026-11-09', 'HEALING & HEALTH', 'James 5:14-15', 'NIV', 'Is anyone among you sick? Let them call the elders of the church to pray over them... And the prayer offered in faith will make the sick person well.'),
(139, DATE '2026-11-10', 'WORK & DILIGENCE', 'Proverbs 14:23', 'NIV', 'All hard work brings a profit, but mere talk leads only to poverty.'),
(140, DATE '2026-11-11', 'WISDOM & DECISIONS', 'Psalm 32:8', 'NIV', 'I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.'),
(141, DATE '2026-11-12', 'FRIENDSHIP', 'Ecclesiastes 4:12', 'NIV', 'Though one may be overpowered, two can defend themselves. A cord of three strands is not quickly broken.'),
(142, DATE '2026-11-13', 'GENEROSITY & GIVING', 'Proverbs 19:17', 'NIV', 'Whoever is kind to the poor lends to the LORD, and he will reward them for what they have done.'),
(143, DATE '2026-11-14', 'HUMILITY', '1 Peter 5:5', 'KJV', 'God resisteth the proud, and giveth grace to the humble.'),
(144, DATE '2026-11-15', 'PRAISE & WORSHIP', 'Psalm 100:1-2', 'NIV', 'Shout for joy to the LORD, all the earth. Worship the LORD with gladness; come before him with joyful songs.'),
(145, DATE '2026-11-16', 'PRAYER', 'James 5:16', 'NIV', 'The prayer of a righteous person is powerful and effective.'),
(146, DATE '2026-11-17', 'REST & SLEEP', 'Psalm 3:5', 'KJV', 'I laid me down and slept; I awaked; for the LORD sustained me.'),
(147, DATE '2026-11-18', 'NEW BEGINNINGS', 'Philippians 3:13-14', 'NIV', 'Forgetting what is behind and straining toward what is ahead, I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.'),
(148, DATE '2026-11-19', 'PERSEVERANCE', '2 Timothy 4:7', 'KJV', 'I have fought a good fight, I have finished my course, I have kept the faith.'),
(149, DATE '2026-11-20', 'JOY & HAPPINESS', 'John 15:11', 'NIV', 'I have told you this so that my joy may be in you and that your joy may be complete.'),
(150, DATE '2026-11-21', 'PEACE & CALM', 'Colossians 3:15', 'NIV', 'Let the peace of Christ rule in your hearts, since as members of one body you were called to peace. And be thankful.'),
(151, DATE '2026-11-22', 'SECURITY & SAFETY', 'Proverbs 3:24', 'NLT', 'You can go to bed without fear; you will lie down and sleep soundly.'),
(152, DATE '2026-11-23', 'ANGER & SELF-CONTROL', 'Proverbs 16:32', 'ESV', 'Whoever is slow to anger is better than the mighty, and he who rules his spirit than he who takes a city.'),
(153, DATE '2026-11-24', 'SADNESS & GRIEF', 'Psalm 30:11', 'NIV', 'You turned my wailing into dancing; you removed my sackcloth and clothed me with joy.'),
(154, DATE '2026-11-25', 'FEAR & ANXIETY', '1 Peter 5:7', 'NIV', 'Cast all your anxiety on him because he cares for you.'),
(155, DATE '2026-11-26', 'HOPE', 'Isaiah 40:31', 'KJV', 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.'),
(156, DATE '2026-11-27', 'LOVE', '1 John 4:19', 'ESV', 'We love because he first loved us.'),
(157, DATE '2026-11-28', 'COMFORT IN SUFFERING', '1 Peter 5:10', 'NIV', 'And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong, firm and steadfast.'),
(158, DATE '2026-11-29', 'GRATITUDE & THANKFULNESS', 'Psalm 9:1', 'ESV', 'I will give thanks to the LORD with my whole heart; I will recount all of your wonderful deeds.'),
(159, DATE '2026-11-30', 'COURAGE & STRENGTH', '1 Corinthians 16:13', 'NIV', 'Be on your guard; stand firm in the faith; be courageous; be strong.'),
(160, DATE '2026-12-01', 'LONELINESS', 'Psalm 25:16', 'ESV', 'Turn to me and be gracious to me, for I am lonely and afflicted.'),
(161, DATE '2026-12-02', 'FORGIVENESS', 'Matthew 6:14', 'NIV', 'For if you forgive other people when they sin against you, your heavenly Father will also forgive you.'),
(162, DATE '2026-12-03', 'PATIENCE', 'Ecclesiastes 7:8', 'NIV', 'The end of a matter is better than its beginning, and patience is better than pride.'),
(163, DATE '2026-12-04', 'CONTENTMENT', 'Proverbs 30:8', 'NIV', 'Keep falsehood and lies far from me; give me neither poverty nor riches, but give me only my daily bread.'),
(164, DATE '2026-12-05', 'DOUBT & FAITH', 'Matthew 17:20', 'NIV', 'Truly I tell you, if you have faith as small as a mustard seed, you can say to this mountain, Move from here to there, and it will move. Nothing will be impossible for you.'),
(165, DATE '2026-12-06', 'GUILT & SHAME', 'Romans 10:11', 'ESV', 'For the Scripture says, Everyone who believes in him will not be put to shame.'),
(166, DATE '2026-12-07', 'WORRY & STRESS', '1 Peter 5:6-7', 'NIV', 'Humble yourselves, therefore, under God''s mighty hand, that he may lift you up in due time. Cast all your anxiety on him because he cares for you.'),
(167, DATE '2026-12-08', 'TRUST IN GOD', 'Psalm 56:3-4', 'ESV', 'When I am afraid, I put my trust in you. In God, whose word I praise, in God I trust; I shall not be afraid.'),
(168, DATE '2026-12-09', 'DISCOURAGEMENT & WEARINESS', 'Matthew 11:29-30', 'NIV', 'Take my yoke upon you and learn from me, for I am gentle and humble in heart, and you will find rest for your souls. For my yoke is easy and my burden is light.'),
(169, DATE '2026-12-10', 'CONFIDENCE & IDENTITY', 'Galatians 2:20', 'ESV', 'I have been crucified with Christ. It is no longer I who live, but Christ who lives in me.'),
(170, DATE '2026-12-11', 'JEALOUSY & ENVY', 'Psalm 37:1', 'KJV', 'Fret not thyself because of evildoers, neither be thou envious against the workers of iniquity.'),
(171, DATE '2026-12-12', 'TEMPTATION', 'James 4:7', 'ESV', 'Submit yourselves therefore to God. Resist the devil, and he will flee from you.'),
(172, DATE '2026-12-13', 'MARRIAGE & RELATIONSHIPS', 'Genesis 2:24', 'ESV', 'Therefore a man shall leave his father and his mother and hold fast to his wife, and they shall become one flesh.'),
(173, DATE '2026-12-14', 'FAMILY & PARENTING', 'Ephesians 6:4', 'NIV', 'Fathers, do not exasperate your children; instead, bring them up in the training and instruction of the Lord.'),
(174, DATE '2026-12-15', 'FINANCES & PROVISION', 'Luke 6:38', 'ESV', 'Give, and it will be given to you. Good measure, pressed down, shaken together, running over, will be put into your lap.'),
(175, DATE '2026-12-16', 'HEALING & HEALTH', '3 John 1:2', 'NIV', 'Dear friend, I pray that you may enjoy good health and that all may go well with you, even as your soul is getting along well.'),
(176, DATE '2026-12-17', 'WORK & DILIGENCE', 'Proverbs 13:4', 'NIV', 'A sluggard''s appetite is never filled, but the desires of the diligent are fully satisfied.'),
(177, DATE '2026-12-18', 'WISDOM & DECISIONS', 'Proverbs 19:21', 'NIV', 'Many are the plans in a person''s heart, but it is the LORD''s purpose that prevails.'),
(178, DATE '2026-12-19', 'FRIENDSHIP', 'Proverbs 18:24', 'ESV', 'A man of many companions may come to ruin, but there is a friend who sticks closer than a brother.'),
(179, DATE '2026-12-20', 'GENEROSITY & GIVING', 'Luke 6:38', 'NIV', 'Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.'),
(180, DATE '2026-12-21', 'HUMILITY', 'Micah 6:8', 'NIV', 'And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.'),
(181, DATE '2026-12-22', 'PRAISE & WORSHIP', 'Hebrews 13:15', 'ESV', 'Through him then let us continually offer up a sacrifice of praise to God, that is, the fruit of lips that acknowledge his name.'),
(182, DATE '2026-12-23', 'PRAYER', '1 John 5:14', 'ESV', 'And this is the confidence that we have toward him, that if we ask anything according to his will he hears us.'),
(183, DATE '2026-12-24', 'REST & SLEEP', 'Psalm 23:2', 'NIV', 'He makes me lie down in green pastures, he leads me beside quiet waters.'),
(184, DATE '2026-12-25', 'NEW BEGINNINGS', 'Ezekiel 36:26', 'ESV', 'And I will give you a new heart, and a new spirit I will put within you.'),
(185, DATE '2026-12-26', 'PERSEVERANCE', '1 Corinthians 9:24', 'NIV', 'Do you not know that in a race all the runners run, but only one gets the prize? Run in such a way as to get the prize.'),
(186, DATE '2026-12-27', 'JOY & HAPPINESS', 'Romans 15:13', 'ESV', 'May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope.'),
(187, DATE '2026-12-28', 'PEACE & CALM', 'John 16:33', 'ESV', 'I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world.'),
(188, DATE '2026-12-29', 'SECURITY & SAFETY', 'Psalm 4:8', 'KJV', 'I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.'),
(189, DATE '2026-12-30', 'ANGER & SELF-CONTROL', 'Colossians 3:8', 'NIV', 'But now you must also rid yourselves of all such things as these: anger, rage, malice, slander, and filthy language from your lips.'),
(190, DATE '2026-12-31', 'SADNESS & GRIEF', '2 Corinthians 1:3-4', 'ESV', 'Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction.'),
(191, DATE '2027-01-01', 'FEAR & ANXIETY', 'Matthew 6:34', 'ESV', 'Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble.'),
(192, DATE '2027-01-02', 'HOPE', 'Psalm 39:7', 'ESV', 'And now, O Lord, for what do I wait? My hope is in you.'),
(193, DATE '2027-01-03', 'LOVE', 'Zephaniah 3:17', 'NIV', 'The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.'),
(194, DATE '2027-01-04', 'COMFORT IN SUFFERING', 'James 1:2-3', 'NIV', 'Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.'),
(195, DATE '2027-01-05', 'GRATITUDE & THANKFULNESS', 'Philippians 4:6', 'NLT', 'Don''t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done.'),
(196, DATE '2027-01-06', 'COURAGE & STRENGTH', 'Psalm 27:14', 'KJV', 'Wait on the LORD: be of good courage, and he shall strengthen thine heart: wait, I say, on the LORD.'),
(197, DATE '2027-01-07', 'LONELINESS', 'Isaiah 41:10', 'NLT', 'Don''t be afraid, for I am with you. Don''t be discouraged, for I am your God. I will strengthen you and help you. I will hold you up with my victorious right hand.'),
(198, DATE '2027-01-08', 'FORGIVENESS', 'Micah 7:18', 'ESV', 'Who is a God like you, pardoning iniquity and passing over transgression for the remnant of his inheritance? He does not retain his anger forever, because he delights in steadfast love.'),
(199, DATE '2027-01-09', 'PATIENCE', 'Lamentations 3:25', 'ESV', 'The LORD is good to those who wait for him, to the soul who seeks him.'),
(200, DATE '2027-01-10', 'CONTENTMENT', 'Ecclesiastes 3:13', 'ESV', 'Also that everyone should eat and drink and take pleasure in all his toil, this is God''s gift to man.'),
(201, DATE '2027-01-11', 'DOUBT & FAITH', 'Proverbs 3:5-6', 'NIV', 'Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.'),
(202, DATE '2027-01-12', 'GUILT & SHAME', 'Hebrews 10:22', 'NIV', 'Let us draw near to God with a sincere heart and with the full assurance that faith brings, having our hearts sprinkled to cleanse us from a guilty conscience.'),
(203, DATE '2027-01-13', 'WORRY & STRESS', 'Psalm 94:19', 'ESV', 'When the cares of my heart are many, your consolations cheer my soul.'),
(204, DATE '2027-01-14', 'TRUST IN GOD', 'Nahum 1:7', 'NIV', 'The LORD is good, a refuge in times of trouble. He cares for those who trust in him.'),
(205, DATE '2027-01-15', 'DISCOURAGEMENT & WEARINESS', 'Psalm 138:3', 'ESV', 'On the day I called, you answered me; my strength of soul you increased.'),
(206, DATE '2027-01-16', 'CONFIDENCE & IDENTITY', 'Philippians 1:6', 'NIV', 'Being confident of this, that he who began a good work in you will carry it on to completion until the day of Christ Jesus.'),
(207, DATE '2027-01-17', 'JEALOUSY & ENVY', 'Proverbs 23:17', 'NIV', 'Do not let your heart envy sinners, but always be zealous for the fear of the LORD.'),
(208, DATE '2027-01-18', 'TEMPTATION', '1 Peter 5:8', 'NIV', 'Be alert and of sober mind. Your enemy the devil prowls around like a roaring lion looking for someone to devour.'),
(209, DATE '2027-01-19', 'MARRIAGE & RELATIONSHIPS', 'Proverbs 18:22', 'KJV', 'Whoso findeth a wife findeth a good thing, and obtaineth favour of the LORD.'),
(210, DATE '2027-01-20', 'FAMILY & PARENTING', 'Proverbs 31:28', 'ESV', 'Her children rise up and call her blessed; her husband also, and he praises her.'),
(211, DATE '2027-01-21', 'FINANCES & PROVISION', 'Proverbs 13:11', 'NIV', 'Dishonest money dwindles away, but whoever gathers money little by little makes it grow.'),
(212, DATE '2027-01-22', 'HEALING & HEALTH', 'Exodus 15:26', 'ESV', 'For I am the LORD, your healer.'),
(213, DATE '2027-01-23', 'WORK & DILIGENCE', 'Proverbs 12:11', 'NIV', 'Those who work their land will have abundant food, but those who chase fantasies have no sense.'),
(214, DATE '2027-01-24', 'WISDOM & DECISIONS', 'James 3:17', 'ESV', 'But the wisdom from above is first pure, then peaceable, gentle, open to reason, full of mercy and good fruits.'),
(215, DATE '2027-01-25', 'FRIENDSHIP', '1 Thessalonians 5:11', 'NIV', 'Therefore encourage one another and build each other up, just as in fact you are doing.'),
(216, DATE '2027-01-26', 'GENEROSITY & GIVING', 'Proverbs 22:9', 'ESV', 'Whoever has a bountiful eye will be blessed, for he shares his bread with the poor.'),
(217, DATE '2027-01-27', 'HUMILITY', 'Proverbs 22:4', 'ESV', 'The reward for humility and fear of the LORD is riches and honor and life.'),
(218, DATE '2027-01-28', 'PRAISE & WORSHIP', 'Psalm 145:3', 'NIV', 'Great is the LORD and most worthy of praise; his greatness no one can fathom.'),
(219, DATE '2027-01-29', 'PRAYER', 'Mark 11:24', 'NIV', 'Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.'),
(220, DATE '2027-01-30', 'REST & SLEEP', 'Proverbs 3:24', 'ESV', 'If you lie down, you will not be afraid; when you lie down, your sleep will be sweet.'),
(221, DATE '2027-01-31', 'NEW BEGINNINGS', 'Revelation 21:5', 'KJV', 'Behold, I make all things new.'),
(222, DATE '2027-02-01', 'PERSEVERANCE', 'Romans 8:25', 'ESV', 'But if we hope for what we do not see, we wait for it with patience.'),
(223, DATE '2027-02-02', 'JOY & HAPPINESS', 'Philippians 4:4', 'KJV', 'Rejoice in the Lord alway: and again I say, Rejoice.'),
(224, DATE '2027-02-03', 'PEACE & CALM', 'Psalm 29:11', 'NIV', 'The LORD gives strength to his people; the LORD blesses his people with peace.'),
(225, DATE '2027-02-04', 'SECURITY & SAFETY', 'Deuteronomy 33:27', 'KJV', 'The eternal God is thy refuge, and underneath are the everlasting arms.'),
(226, DATE '2027-02-05', 'ANGER & SELF-CONTROL', 'Psalm 37:8', 'NLT', 'Stop being angry! Turn from your rage! Do not lose your temper, it only leads to harm.'),
(227, DATE '2027-02-06', 'SADNESS & GRIEF', 'Psalm 56:8', 'NLT', 'You keep track of all my sorrows. You have collected all my tears in your bottle. You have recorded each one in your book.'),
(228, DATE '2027-02-07', 'FEAR & ANXIETY', 'Joshua 1:9', 'NIV', 'Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.'),
(229, DATE '2027-02-08', 'HOPE', 'Hebrews 11:1', 'NIV', 'Now faith is confidence in what we hope for and assurance about what we do not see.'),
(230, DATE '2027-02-09', 'LOVE', '1 John 4:7', 'NIV', 'Dear friends, let us love one another, for love comes from God. Everyone who loves has been born of God and knows God.'),
(231, DATE '2027-02-10', 'COMFORT IN SUFFERING', 'Psalm 73:26', 'ESV', 'My flesh and my heart may fail, but God is the strength of my heart and my portion forever.'),
(232, DATE '2027-02-11', 'GRATITUDE & THANKFULNESS', 'Psalm 136:1', 'NIV', 'Give thanks to the LORD, for he is good. His love endures forever.'),
(233, DATE '2027-02-12', 'COURAGE & STRENGTH', 'Ephesians 6:10', 'NIV', 'Finally, be strong in the Lord and in his mighty power.'),
(234, DATE '2027-02-13', 'LONELINESS', 'Psalm 139:7-8', 'NIV', 'Where can I go from your Spirit? Where can I flee from your presence? If I go up to the heavens, you are there; if I make my bed in the depths, you are there.'),
(235, DATE '2027-02-14', 'FORGIVENESS', 'Isaiah 1:18', 'KJV', 'Though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.'),
(236, DATE '2027-02-15', 'PATIENCE', 'Isaiah 40:31', 'NIV', 'But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.'),
(237, DATE '2027-02-16', 'CONTENTMENT', '1 Timothy 6:7-8', 'NIV', 'For we brought nothing into the world, and we can take nothing out of it. But if we have food and clothing, we will be content with that.'),
(238, DATE '2027-02-17', 'DOUBT & FAITH', 'Romans 10:17', 'ESV', 'So faith comes from hearing, and hearing through the word of Christ.'),
(239, DATE '2027-02-18', 'GUILT & SHAME', 'Psalm 103:10', 'NLT', 'He does not punish us for all our sins; he does not deal harshly with us, as we deserve.'),
(240, DATE '2027-02-19', 'WORRY & STRESS', 'Proverbs 12:25', 'NIV', 'Anxiety weighs down the heart, but a kind word cheers it up.'),
(241, DATE '2027-02-20', 'TRUST IN GOD', 'Psalm 62:8', 'ESV', 'Trust in him at all times, O people; pour out your heart before him; God is a refuge for us.'),
(242, DATE '2027-02-21', 'DISCOURAGEMENT & WEARINESS', 'Joshua 1:9', 'NLT', 'This is my command, be strong and courageous! Do not be afraid or discouraged. For the LORD your God is with you wherever you go.'),
(243, DATE '2027-02-22', 'CONFIDENCE & IDENTITY', 'Psalm 138:8', 'NLT', 'The LORD will work out his plans for my life, for your faithful love, O LORD, endures forever. Don''t abandon me, for you made me.'),
(244, DATE '2027-02-23', 'JEALOUSY & ENVY', 'Galatians 5:22-23', 'NIV', 'But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.'),
(245, DATE '2027-02-24', 'TEMPTATION', '2 Peter 2:9', 'NIV', 'The Lord knows how to rescue the godly from trials and to hold the unrighteous for punishment on the day of judgment.'),
(246, DATE '2027-02-25', 'MARRIAGE & RELATIONSHIPS', 'Song of Solomon 8:7', 'NIV', 'Many waters cannot quench love; rivers cannot sweep it away.'),
(247, DATE '2027-02-26', 'FAMILY & PARENTING', 'Ephesians 6:1', 'NIV', 'Children, obey your parents in the Lord, for this is right.'),
(248, DATE '2027-02-27', 'FINANCES & PROVISION', '1 Timothy 6:10', 'KJV', 'For the love of money is the root of all evil.'),
(249, DATE '2027-02-28', 'HEALING & HEALTH', 'Psalm 147:3', 'NLT', 'He heals the brokenhearted and bandages their wounds.'),
(250, DATE '2027-03-01', 'WORK & DILIGENCE', '2 Thessalonians 3:10', 'ESV', 'If anyone is not willing to work, let him not eat.'),
(251, DATE '2027-03-02', 'WISDOM & DECISIONS', 'Proverbs 9:10', 'NIV', 'The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.'),
(252, DATE '2027-03-03', 'FRIENDSHIP', 'Proverbs 27:9', 'NLT', 'The heartfelt counsel of a friend is as sweet as perfume and incense.'),
(253, DATE '2027-03-04', 'GENEROSITY & GIVING', 'Matthew 6:21', 'NIV', 'For where your treasure is, there your heart will be also.'),
(254, DATE '2027-03-05', 'HUMILITY', 'Matthew 23:12', 'NIV', 'For those who exalt themselves will be humbled, and those who humble themselves will be exalted.'),
(255, DATE '2027-03-06', 'PRAISE & WORSHIP', 'John 4:24', 'NIV', 'God is spirit, and his worshipers must worship in the Spirit and in truth.'),
(256, DATE '2027-03-07', 'PRAYER', 'Jeremiah 33:3', 'KJV', 'Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.'),
(257, DATE '2027-03-08', 'REST & SLEEP', 'Mark 6:31', 'NIV', 'Come with me by yourselves to a quiet place and get some rest.'),
(258, DATE '2027-03-09', 'NEW BEGINNINGS', 'Isaiah 40:31', 'NLT', 'But those who trust in the LORD will find new strength. They will soar high on wings like eagles.'),
(259, DATE '2027-03-10', 'PERSEVERANCE', 'James 1:12', 'NIV', 'Blessed is the one who perseveres under trial because, having stood the test, that person will receive the crown of life.'),
(260, DATE '2027-03-11', 'JOY & HAPPINESS', 'Psalm 28:7', 'NIV', 'The LORD is my strength and my shield; my heart trusts in him, and he helps me. My heart leaps for joy, and with my song I praise him.'),
(261, DATE '2027-03-12', 'PEACE & CALM', '2 Thessalonians 3:16', 'ESV', 'Now may the Lord of peace himself give you peace at all times in every way. The Lord be with you all.'),
(262, DATE '2027-03-13', 'SECURITY & SAFETY', 'Psalm 27:1', 'NIV', 'The LORD is my light and my salvation, whom shall I fear? The LORD is the stronghold of my life, of whom shall I be afraid?'),
(263, DATE '2027-03-14', 'ANGER & SELF-CONTROL', 'Proverbs 29:11', 'NIV', 'Fools give full vent to their rage, but the wise bring calm in the end.'),
(264, DATE '2027-03-15', 'SADNESS & GRIEF', 'John 11:35', 'KJV', 'Jesus wept.'),
(265, DATE '2027-03-16', 'FEAR & ANXIETY', 'Psalm 56:3', 'ESV', 'When I am afraid, I put my trust in you.'),
(266, DATE '2027-03-17', 'HOPE', 'Romans 5:5', 'ESV', 'And hope does not put us to shame, because God''s love has been poured into our hearts through the Holy Spirit who has been given to us.'),
(267, DATE '2027-03-18', 'LOVE', 'John 13:34', 'ESV', 'A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another.'),
(268, DATE '2027-03-19', 'COMFORT IN SUFFERING', 'Isaiah 41:13', 'NIV', 'For I am the LORD your God who takes hold of your right hand and says to you, Do not fear; I will help you.'),
(269, DATE '2027-03-20', 'GRATITUDE & THANKFULNESS', 'Ephesians 5:20', 'ESV', 'Giving thanks always and for everything to God the Father in the name of our Lord Jesus Christ.'),
(270, DATE '2027-03-21', 'COURAGE & STRENGTH', 'Exodus 15:2', 'ESV', 'The LORD is my strength and my song, and he has become my salvation; this is my God, and I will praise him.'),
(271, DATE '2027-03-22', 'LONELINESS', 'John 14:18', 'ESV', 'I will not leave you as orphans; I will come to you.'),
(272, DATE '2027-03-23', 'FORGIVENESS', 'Acts 3:19', 'NIV', 'Repent, then, and turn to God, so that your sins may be wiped out, that times of refreshing may come from the Lord.'),
(273, DATE '2027-03-24', 'PATIENCE', 'Romans 8:25', 'NIV', 'But if we hope for what we do not yet have, we wait for it patiently.'),
(274, DATE '2027-03-25', 'CONTENTMENT', 'Psalm 16:6', 'NLT', 'The land you have given me is a pleasant land. What a wonderful inheritance!'),
(275, DATE '2027-03-26', 'DOUBT & FAITH', 'John 20:29', 'NIV', 'Then Jesus told him, Because you have seen me, you have believed; blessed are those who have not seen and yet have believed.'),
(276, DATE '2027-03-27', 'GUILT & SHAME', 'Isaiah 43:25', 'ESV', 'I, I am he who blots out your transgressions for my own sake, and I will not remember your sins.'),
(277, DATE '2027-03-28', 'WORRY & STRESS', 'Luke 12:25-26', 'NLT', 'Can all your worries add a single moment to your life? And if worry can''t accomplish a little thing like that, what''s the use of worrying over bigger things?'),
(278, DATE '2027-03-29', 'TRUST IN GOD', 'Jeremiah 17:7-8', 'NIV', 'But blessed is the one who trusts in the LORD, whose confidence is in him. They will be like a tree planted by the water that sends out its roots by the stream.'),
(279, DATE '2027-03-30', 'DISCOURAGEMENT & WEARINESS', 'Isaiah 41:10', 'ESV', 'Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.'),
(280, DATE '2027-03-31', 'CONFIDENCE & IDENTITY', 'Romans 8:37', 'NIV', 'No, in all these things we are more than conquerors through him who loved us.'),
(281, DATE '2027-04-01', 'JEALOUSY & ENVY', 'James 4:2', 'NLT', 'You want what you don''t have, so you scheme and kill to get it. You are jealous of what others have, but you can''t get it.'),
(282, DATE '2027-04-02', 'TEMPTATION', 'Hebrews 2:18', 'ESV', 'For because he himself has suffered when tempted, he is able to help those who are being tempted.'),
(283, DATE '2027-04-03', 'MARRIAGE & RELATIONSHIPS', '1 Peter 4:8', 'ESV', 'Above all, keep loving one another earnestly, since love covers a multitude of sins.'),
(284, DATE '2027-04-04', 'FAMILY & PARENTING', '3 John 1:4', 'NLT', 'I could have no greater joy than to hear that my children are following the truth.'),
(285, DATE '2027-04-05', 'FINANCES & PROVISION', 'Matthew 6:24', 'ESV', 'No one can serve two masters... You cannot serve God and money.'),
(286, DATE '2027-04-06', 'HEALING & HEALTH', 'Matthew 9:22', 'NIV', 'Jesus turned and saw her. Take heart, daughter, he said, your faith has healed you.'),
(287, DATE '2027-04-07', 'WORK & DILIGENCE', 'Proverbs 22:29', 'NIV', 'Do you see someone skilled in their work? They will serve before kings; they will not serve before officials of low rank.'),
(288, DATE '2027-04-08', 'WISDOM & DECISIONS', 'Isaiah 30:21', 'NLT', 'Your own ears will hear him. Right behind you a voice will say, This is the way you should go, whether to the right or to the left.'),
(289, DATE '2027-04-09', 'FRIENDSHIP', 'Romans 12:15', 'ESV', 'Rejoice with those who rejoice, weep with those who weep.'),
(290, DATE '2027-04-10', 'GENEROSITY & GIVING', '1 Timothy 6:18', 'NIV', 'Command them to do good, to be rich in good deeds, and to be generous and willing to share.'),
(291, DATE '2027-04-11', 'HUMILITY', 'Colossians 3:12', 'NIV', 'Clothe yourselves with compassion, kindness, humility, gentleness and patience.'),
(292, DATE '2027-04-12', 'PRAISE & WORSHIP', 'Psalm 96:9', 'ESV', 'Worship the LORD in the splendor of holiness; tremble before him, all the earth!'),
(293, DATE '2027-04-13', 'PRAYER', 'Matthew 6:6', 'NIV', 'But when you pray, go into your room, close the door and pray to your Father, who is unseen.'),
(294, DATE '2027-04-14', 'REST & SLEEP', 'Hebrews 4:9-10', 'ESV', 'So then, there remains a Sabbath rest for the people of God, for whoever has entered God''s rest has also rested from his works.'),
(295, DATE '2027-04-15', 'NEW BEGINNINGS', 'Isaiah 43:18', 'NIV', 'Forget the former things; do not dwell on the past.'),
(296, DATE '2027-04-16', 'PERSEVERANCE', 'Philippians 3:14', 'ESV', 'I press on toward the goal for the prize of the upward call of God in Christ Jesus.'),
(297, DATE '2027-04-17', 'JOY & HAPPINESS', 'Proverbs 17:22', 'NLT', 'A cheerful heart is good medicine, but a broken spirit saps a person''s strength.'),
(298, DATE '2027-04-18', 'PEACE & CALM', 'Isaiah 32:17', 'NIV', 'The fruit of that righteousness will be peace; its effect will be quietness and confidence forever.'),
(299, DATE '2027-04-19', 'SECURITY & SAFETY', 'Psalm 32:7', 'NIV', 'You are my hiding place; you will protect me from trouble and surround me with songs of deliverance.'),
(300, DATE '2027-04-20', 'ANGER & SELF-CONTROL', 'Ecclesiastes 7:9', 'ESV', 'Be not quick in your spirit to become angry, for anger lodges in the heart of fools.'),
(301, DATE '2027-04-21', 'SADNESS & GRIEF', 'Isaiah 53:4', 'NIV', 'Surely he took up our pain and bore our suffering, yet we considered him punished by God, stricken by him, and afflicted.'),
(302, DATE '2027-04-22', 'FEAR & ANXIETY', 'Deuteronomy 31:6', 'NIV', 'Be strong and courageous. Do not be afraid or terrified because of them, for the LORD your God goes with you; he will never leave you nor forsake you.'),
(303, DATE '2027-04-23', 'HOPE', 'Psalm 71:14', 'NIV', 'As for me, I will always have hope; I will praise you more and more.'),
(304, DATE '2027-04-24', 'LOVE', '1 Corinthians 13:13', 'KJV', 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.'),
(305, DATE '2027-04-25', 'COMFORT IN SUFFERING', '2 Corinthians 12:9', 'NIV', 'But he said to me, My grace is sufficient for you, for my power is made perfect in weakness.'),
(306, DATE '2027-04-26', 'GRATITUDE & THANKFULNESS', 'Colossians 2:7', 'NIV', 'Rooted and built up in him, strengthened in the faith as you were taught, and overflowing with thankfulness.'),
(307, DATE '2027-04-27', 'COURAGE & STRENGTH', '2 Corinthians 12:10', 'NLT', 'For when I am weak, then I am strong.'),
(308, DATE '2027-04-28', 'LONELINESS', 'Psalm 27:10', 'NIV', 'Though my father and mother forsake me, the LORD will receive me.'),
(309, DATE '2027-04-29', 'FORGIVENESS', 'Luke 6:37', 'ESV', 'Judge not, and you will not be judged; condemn not, and you will not be condemned; forgive, and you will be forgiven.'),
(310, DATE '2027-04-30', 'PATIENCE', 'Psalm 27:14', 'ESV', 'Wait for the LORD; be strong, and let your heart take courage; wait for the LORD!'),
(311, DATE '2027-05-01', 'CONTENTMENT', 'Matthew 6:33', 'ESV', 'But seek first the kingdom of God and his righteousness, and all these things will be added to you.'),
(312, DATE '2027-05-02', 'DOUBT & FAITH', 'Isaiah 40:8', 'ESV', 'The grass withers, the flower fades, but the word of our God will stand forever.'),
(313, DATE '2027-05-03', 'GUILT & SHAME', '1 John 3:20', 'NIV', 'If our hearts condemn us, we know that God is greater than our hearts, and he knows everything.'),
(314, DATE '2027-05-04', 'WORRY & STRESS', 'Psalm 46:10', 'NIV', 'Be still, and know that I am God; I will be exalted among the nations, I will be exalted in the earth.'),
(315, DATE '2027-05-05', 'TRUST IN GOD', 'Psalm 28:7', 'ESV', 'The LORD is my strength and my shield; in him my heart trusts, and I am helped; my heart exults, and with my song I give thanks to him.'),
(316, DATE '2027-05-06', 'DISCOURAGEMENT & WEARINESS', 'Psalm 34:17', 'NIV', 'The righteous cry out, and the LORD hears them; he delivers them from all their troubles.'),
(317, DATE '2027-05-07', 'CONFIDENCE & IDENTITY', '2 Corinthians 3:5', 'ESV', 'Not that we are sufficient in ourselves to claim anything as coming from us, but our sufficiency is from God.'),
(318, DATE '2027-05-08', 'JEALOUSY & ENVY', 'Ecclesiastes 4:4', 'ESV', 'Then I saw that all toil and all skill in work come from a man''s envy of his neighbor. This also is vanity and a striving after wind.'),
(319, DATE '2027-05-09', 'TEMPTATION', 'Psalm 119:11', 'KJV', 'Thy word have I hid in mine heart, that I might not sin against thee.'),
(320, DATE '2027-05-10', 'MARRIAGE & RELATIONSHIPS', 'Mark 10:9', 'NIV', 'Therefore what God has joined together, let no one separate.'),
(321, DATE '2027-05-11', 'FAMILY & PARENTING', 'Psalm 103:17', 'NIV', 'But from everlasting to everlasting the LORD''s love is with those who fear him, and his righteousness with their children''s children.'),
(322, DATE '2027-05-12', 'FINANCES & PROVISION', 'Proverbs 22:7', 'NIV', 'The rich rule over the poor, and the borrower is slave to the lender.'),
(323, DATE '2027-05-13', 'HEALING & HEALTH', 'Proverbs 4:20-22', 'NIV', 'My son, pay attention to what I say... for they are life to those who find them and health to one''s whole body.'),
(324, DATE '2027-05-14', 'WORK & DILIGENCE', '1 Corinthians 15:58', 'NIV', 'Always give yourselves fully to the work of the Lord, because you know that your labor in the Lord is not in vain.'),
(325, DATE '2027-05-15', 'WISDOM & DECISIONS', 'Colossians 3:16', 'ESV', 'Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom.'),
(326, DATE '2027-05-16', 'FRIENDSHIP', 'Proverbs 13:20', 'NIV', 'Walk with the wise and become wise, for a companion of fools suffers harm.'),
(327, DATE '2027-05-17', 'GENEROSITY & GIVING', 'Proverbs 3:27', 'ESV', 'Do not withhold good from those to whom it is due, when it is in your power to do it.'),
(328, DATE '2027-05-18', 'HUMILITY', 'Proverbs 16:18', 'KJV', 'Pride goeth before destruction, and an haughty spirit before a fall.'),
(329, DATE '2027-05-19', 'PRAISE & WORSHIP', 'Psalm 103:1', 'NLT', 'Let all that I am praise the LORD; with my whole heart, I will praise his holy name.'),
(330, DATE '2027-05-20', 'PRAYER', 'Romans 8:26', 'ESV', 'Likewise the Spirit helps us in our weakness. For we do not know what to pray for as we ought, but the Spirit himself intercedes for us.'),
(331, DATE '2027-05-21', 'REST & SLEEP', 'Psalm 116:7', 'NLT', 'Let my soul be at rest again, for the LORD has been good to me.'),
(332, DATE '2027-05-22', 'NEW BEGINNINGS', 'Psalm 40:3', 'NIV', 'He put a new song in my mouth, a hymn of praise to our God. Many will see and fear the LORD and put their trust in him.'),
(333, DATE '2027-05-23', 'PERSEVERANCE', 'Hebrews 10:36', 'NIV', 'You need to persevere so that when you have done the will of God, you will receive what he has promised.'),
(334, DATE '2027-05-24', 'JOY & HAPPINESS', '1 Peter 1:8', 'ESV', 'Though you have not seen him, you love him. Though you do not now see him, you believe in him and rejoice with joy that is inexpressible and filled with glory.'),
(335, DATE '2027-05-25', 'PEACE & CALM', 'Numbers 6:24-26', 'NLT', 'May the LORD bless you and protect you. May the LORD smile on you and be gracious to you. May the LORD show you his favor and give you his peace.'),
(336, DATE '2027-05-26', 'SECURITY & SAFETY', 'Proverbs 1:33', 'ESV', 'But whoever listens to me will dwell secure and will be at ease, without dread of disaster.'),
(337, DATE '2027-05-27', 'ANGER & SELF-CONTROL', 'Proverbs 19:11', 'NIV', 'A person''s wisdom yields patience; it is to one''s glory to overlook an offense.'),
(338, DATE '2027-05-28', 'SADNESS & GRIEF', 'Psalm 42:11', 'NIV', 'Why, my soul, are you downcast? Why so disturbed within me? Put your hope in God, for I will yet praise him, my Savior and my God.'),
(339, DATE '2027-05-29', 'FEAR & ANXIETY', 'Isaiah 43:1', 'NLT', 'Do not be afraid, for I have ransomed you. I have called you by name; you are mine.'),
(340, DATE '2027-05-30', 'HOPE', 'Jeremiah 17:7', 'NLT', 'But blessed are those who trust in the LORD and have made the LORD their hope and confidence.'),
(341, DATE '2027-05-31', 'LOVE', 'Jeremiah 31:3', 'NLT', 'Long ago the LORD said to Israel: I have loved you, my people, with an everlasting love. With unfailing love I have drawn you to myself.'),
(342, DATE '2027-06-01', 'COMFORT IN SUFFERING', 'Psalm 46:1-2', 'NLT', 'God is our refuge and strength, always ready to help in times of trouble. So we will not fear when earthquakes come and the mountains crumble into the sea.'),
(343, DATE '2027-06-02', 'GRATITUDE & THANKFULNESS', 'Psalm 95:2', 'NLT', 'Let us come to him with thanksgiving. Let us sing psalms of praise to him.'),
(344, DATE '2027-06-03', 'COURAGE & STRENGTH', 'Psalm 31:24', 'NIV', 'Be strong and take heart, all you who hope in the LORD.'),
(345, DATE '2027-06-04', 'LONELINESS', 'Genesis 28:15', 'NIV', 'I am with you and will watch over you wherever you go, and I will bring you back to this land. I will not leave you until I have done what I have promised you.'),
(346, DATE '2027-06-05', 'FORGIVENESS', 'Psalm 32:5', 'NIV', 'Then I acknowledged my sin to you and did not cover up my iniquity. I said, I will confess my transgressions to the LORD. And you forgave the guilt of my sin.'),
(347, DATE '2027-06-06', 'PATIENCE', 'Colossians 1:11', 'NLT', 'We also pray that you will be strengthened with all his glorious power so you will have all the endurance and patience you need.'),
(348, DATE '2027-06-07', 'CONTENTMENT', 'Psalm 131:2', 'NIV', 'But I have calmed and quieted myself, I am like a weaned child with its mother; like a weaned child I am content.'),
(349, DATE '2027-06-08', 'DOUBT & FAITH', 'Jude 1:22', 'NIV', 'Be merciful to those who doubt.'),
(350, DATE '2027-06-09', 'GUILT & SHAME', 'Joel 2:25', 'KJV', 'And I will restore to you the years that the locust hath eaten.'),
(351, DATE '2027-06-10', 'WORRY & STRESS', 'Isaiah 26:3', 'NLT', 'You will keep in perfect peace all who trust in you, all whose thoughts are fixed on you!'),
(352, DATE '2027-06-11', 'TRUST IN GOD', 'Proverbs 16:3', 'NLT', 'Commit your actions to the LORD, and your plans will succeed.'),
(353, DATE '2027-06-12', 'DISCOURAGEMENT & WEARINESS', '2 Thessalonians 3:13', 'ESV', 'As for you, brothers, do not grow weary in doing good.'),
(354, DATE '2027-06-13', 'CONFIDENCE & IDENTITY', 'Hebrews 4:16', 'NIV', 'Let us then approach God''s throne of grace with confidence, so that we may receive mercy and find grace to help us in our time of need.'),
(355, DATE '2027-06-14', 'JEALOUSY & ENVY', 'Job 5:2', 'NIV', 'Resentment kills a fool, and envy slays the simple.'),
(356, DATE '2027-06-15', 'TEMPTATION', 'Galatians 5:16', 'NIV', 'So I say, walk by the Spirit, and you will not gratify the desires of the flesh.'),
(357, DATE '2027-06-16', 'MARRIAGE & RELATIONSHIPS', 'Romans 12:10', 'NLT', 'Love each other with genuine affection, and take delight in honoring each other.'),
(358, DATE '2027-06-17', 'FAMILY & PARENTING', 'Proverbs 17:6', 'ESV', 'Grandchildren are the crown of the aged, and the glory of children is their fathers.'),
(359, DATE '2027-06-18', 'FINANCES & PROVISION', 'Psalm 37:25', 'NLT', 'Once I was young, and now I am old. Yet I have never seen the godly abandoned or their children begging for bread.'),
(360, DATE '2027-06-19', 'HEALING & HEALTH', '1 Peter 2:24', 'ESV', 'By his wounds you have been healed.'),
(361, DATE '2027-06-20', 'WORK & DILIGENCE', 'Proverbs 21:5', 'NLT', 'Good planning and hard work lead to prosperity, but hasty shortcuts lead to poverty.'),
(362, DATE '2027-06-21', 'WISDOM & DECISIONS', 'Proverbs 11:14', 'NIV', 'For lack of guidance a nation falls, but victory is won through many advisers.'),
(363, DATE '2027-06-22', 'FRIENDSHIP', 'Galatians 6:2', 'NIV', 'Carry each other''s burdens, and in this way you will fulfill the law of Christ.'),
(364, DATE '2027-06-23', 'GENEROSITY & GIVING', '2 Corinthians 9:8', 'NLT', 'And God will generously provide all you need. Then you will always have everything you need and plenty left over to share.'),
(365, DATE '2027-06-24', 'HUMILITY', 'Luke 14:11', 'ESV', 'For everyone who exalts himself will be humbled, and he who humbles himself will be exalted.');

-- Down Migration

DROP TABLE IF EXISTS daily_verses;
